# Generated by Django 4.0 on 2022-03-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220317_1423'),
        ('main', '0007_movie_videofile'),
    ]

    operations = [
    ]
