# Generated by Django 4.0 on 2022-03-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_0007_auto_20220317_1423_0007_movie_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='videofile',
        ),
    ]
